

@startuml

title Real-time Bidding canonical model

hide circle

hide empty members

' hide Segment
' hide Demographics
' hide Location
' hide Creative
' hide Advertiser
' hide ActivityEvent
' hide Purchase



' skinparam class {
'   BackgroundColor PaleGreen
'   ArrowColor SeaGreen
'   BorderColor SpringGreen
' }
' skinparam stereotypeCBackgroundColor YellowGreen




class UserProfile  #LightGoldenRodYellow ##red{
  - String id
  - Date createdAt
  - Date updatedAt
  - Demographics demographics
  - List<String> interests
  - Location location
  - List<ActivityEvent> activity
  - List<Purchase> purchases
  - List<String> lineitemIds
  - List<String> AudienceIds
}

class Demographics  #LightGoldenRodYellow ##red{
  +String ageRange
  +String gender
  +String location
  ...etc
}

class Location #LightGoldenRodYellow ##red{
  +String city
  +String state
  +String country
  ...etc
}

class ActivityEvent {
  +String url
  +Date timestamp
  ...etc
}

class Purchase {
  +String itemId
  +Date purchaseDate
  +float amount
  ...etc
}

UserProfile "1" *-- "1" Demographics  #red
UserProfile "1" *-- "1" Location #red
UserProfile "1" *-- "1..*" ActivityEvent : activity
UserProfile "1" *-- "1..*" Purchase : purchases


enum LineitemStatus #LightGoldenRodYellow ##red{
    DRAFT
    ACTIVE
    PAUSED
    FINISHED
}

class Campaign {
    - String id
    - String name
    - List<String> lineitemIds
    - Float budget
    - DateTime startDate
    - DateTime endDate
    - Advertiser advertiser
}


class Lineitem #LightGoldenRodYellow ##red{
    - String id
    - String campaignId
    - Audience audience
    - List<Creative> creatives
    - Float budget
    - DateTime startDate
    - DateTime endDate
    - LineitemStatus status
}

class Audience {
    - String id
    - String name
    - List<Segment> segments
}

class Segment {
  +String id
  +String name
  ...etc
}




class Advertiser {
    - String id
    - String name
    - List<Campaign> campaigns
}


class Creative {
    - String id
    - String name
    - String url
    - String format
    - String size
    - String type
}

Campaign "*" <..> "1..*" Lineitem : lineitems
Advertiser "1" <.> "*" Campaign : campaigns
Advertiser "*" ..> "1..*" Creative : creatives
Creative "*" <- "*" Lineitem : creatives
Lineitem "*" <..> "1" Audience : audience
Lineitem - LineitemStatus  #red
Lineitem "1..50" .. "*" UserProfile   #red
Segment "1..*" <.* "*" Audience : segments
Audience "*" <.. "1..*" UserProfile


@enduml



@startuml

title Audience model

hide circle
hide empty members

class Audience {
    - String id
    - String name
    - List<Segment> segments
}

class Segment {
  +String id
  +String name
  +String description
  +Date creationDate
  +Date lastUpdated
  +Criteria criteria
  +String source
  +Date expiryDate
  +int audienceSize
  +String segmentType
  +List<Lineitems> lineitems
  +PerformanceMetrics performanceMetrics
}

class Criteria {
  +Demographics demographics
  +BehavioralData behavioralData
  +List<String> interests
  ...etc
}

class Demographics {
  +String ageRange
  +String gender
  +String location
  ...etc
}

class BehavioralData {
  +List<String> browsingHistory
  +List<String> purchaseHistory
  ...etc
}

class PerformanceMetrics {
  +float clickThroughRate
  +float conversionRate
  ...etc
}

Audience "*" .> "1..*" Segment : segments

Segment "1" -- "1" Criteria
Criteria "1" -- "1" Demographics
Criteria "1" -- "1" BehavioralData
Segment "1" -- "1" PerformanceMetrics
Segment "*" . "1..*" Lineitems : lineitems
@enduml
