@startuml

participant "Ad Exchange" as adExchange
participant "DSP" as dsp
participant "RTB bidder" as rtbBidder
Database "Aerospike cluster" as aerospike

autonumber



adExchange -> dsp: Bid Request
activate dsp
dsp -> rtbBidder: Bid Request
activate rtbBidder
rtbBidder -> aerospike: Get UserProfile
activate aerospike
aerospike --> rtbBidder: UserProfile ~ 0.8ms
deactivate aerospike
rtbBidder -> aerospike: Batch read active line items - max 50
activate aerospike
aerospike --> rtbBidder: Active line items ~5ms - 9ms
deactivate aerospike

rtbBidder -> rtbBidder: Choose the best linitem

rtbBidder -> rtbBidder: Create bid response

rtbBidder -> dsp: Bid Response
deactivate rtbBidder
dsp -> adExchange: Bid Response
deactivate dsp




@enduml