services:
  usecases-core:
    image: aerospike/aerospike-server-enterprise:latest
    container_name: core-usecases
    command: --config-file /etc/aerospike/aerospike.conf
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/config/aerospike:/etc/aerospike
      - ${PWD}/data/aerospike:/opt/aerospike/data
    healthcheck:
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - usecases

  usecases-vector:
    image: aerospike/aerospike-vector-search:0.11.1
    container_name: vector-usecases
    volumes:
      - ${PWD}/config/vector:/etc/aerospike-vector-search
    depends_on:
      usecases-core:
        condition: service_healthy
    ports:
      - 5500:5500
      - 5040:5040
      - 5001:5001
    networks:
      - usecases

networks:
  usecases:
    driver: bridge
