package com.aerospike.usecases.rtb;

import java.util.Date;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

import com.aerospike.usecases.rtb.model.Campaign;
import com.aerospike.usecases.rtb.model.Creative;
import com.aerospike.usecases.rtb.model.Demographics;
import com.aerospike.usecases.rtb.model.Gender;
import com.aerospike.usecases.rtb.model.Lineitem;
import com.aerospike.usecases.rtb.model.LineitemStatus;
import com.aerospike.usecases.rtb.model.Location;
import com.aerospike.usecases.rtb.model.Size;
import com.aerospike.usecases.rtb.model.Publisher;
import com.aerospike.usecases.rtb.model.bid.Bid;
import com.aerospike.usecases.rtb.model.bid.BidRequest;
import com.aerospike.usecases.rtb.model.bid.BidResponse;
import com.aerospike.usecases.rtb.model.bid.SeatBid;

import java.util.UUID;

public class RandomData {
    /**
     * A static list of Location objects generated by the generateLocations()
     * method. This list serves as a cache of location data for use in the
     * application.
     */
    static List<Location> locations = generateLocations();

    /**
     * A list of IAB (Interactive Advertising Bureau) standard banner sizes. This
     * list is used to define the standard dimensions for banner advertisements.
     */
    static List<Size> iabBannerSizes = getIABBannerSizes();

    /**
     * A static list of IAB (Interactive Advertising Bureau) content categories.
     * These categories are used to classify and organize content for real-time
     * bidding in advertising.
     */
    static List<String> iabContentCategories = iabContentCatergories();

    /**
     * Generates a list of predefined locations from around the world. Each location
     * includes details such as country, country code, state/province, city, postal
     * code, latitude, and longitude.
     *
     * @return a list of Location objects representing various cities globally.
     */
    private static List<Location> generateLocations() {
        List<Location> locations = new ArrayList<>();

        locations.add(new Location("United States", "US", "California", "Los Angeles", "90001", 34.0522, -118.2437));
        locations.add(new Location("Canada", "CA", "Ontario", "Toronto", "M5H", 43.65107, -79.347015));
        locations.add(new Location("United Kingdom", "GB", "England", "London", "EC1A", 51.5074, -0.1278));
        locations.add(new Location("Germany", "DE", "Berlin", "Berlin", "10117", 52.5200, 13.4050));
        locations.add(new Location("France", "FR", "Île-de-France", "Paris", "75001", 48.8566, 2.3522));
        locations.add(new Location("Japan", "JP", "Tokyo", "Tokyo", "100-0001", 35.6895, 139.6917));
        locations.add(new Location("Australia", "AU", "New South Wales", "Sydney", "2000", -33.8688, 151.2093));
        locations.add(new Location("Brazil", "BR", "São Paulo", "São Paulo", "01000-000", -23.5505, -46.6333));
        locations.add(new Location("India", "IN", "Maharashtra", "Mumbai", "400001", 19.0760, 72.8777));
        locations.add(new Location("China", "CN", "Beijing", "Beijing", "100000", 39.9042, 116.4074));
        locations.add(new Location("South Africa", "ZA", "Gauteng", "Johannesburg", "2000", -26.2041, 28.0473));
        locations.add(new Location("Russia", "RU", "Moscow", "Moscow", "101000", 55.7558, 37.6176));
        locations.add(new Location("Mexico", "MX", "Mexico City", "Mexico City", "06000", 19.4326, -99.1332));
        locations.add(new Location("South Korea", "KR", "Seoul", "Seoul", "100-011", 37.5665, 126.9780));
        locations.add(new Location("Italy", "IT", "Lazio", "Rome", "00118", 41.9028, 12.4964));
        locations.add(new Location("Spain", "ES", "Madrid", "Madrid", "28001", 40.4168, -3.7038));
        locations.add(new Location("Netherlands", "NL", "North Holland", "Amsterdam", "1012", 52.3676, 4.9041));
        locations.add(new Location("Singapore", "SG", "Singapore", "Singapore", "179431", 1.3521, 103.8198));
        locations.add(new Location("Sweden", "SE", "Stockholm", "Stockholm", "111 29", 59.3293, 18.0686));
        locations.add(new Location("Switzerland", "CH", "Zurich", "Zurich", "8001", 47.3769, 8.5417));
        locations.add(new Location("United Arab Emirates", "AE", "Dubai", "Dubai", "00000", 25.276987, 55.296249));
        locations.add(new Location("Saudi Arabia", "SA", "Riyadh", "Riyadh", "11564", 24.7136, 46.6753));
        locations.add(new Location("Turkey", "TR", "Istanbul", "Istanbul", "34110", 41.0082, 28.9784));
        locations.add(new Location("Poland", "PL", "Masovian Voivodeship", "Warsaw", "00-001", 52.2297, 21.0122));
        locations.add(new Location("Argentina", "AR", "Buenos Aires", "Buenos Aires", "C1002", -34.6037, -58.3816));
        locations.add(new Location("Thailand", "TH", "Bangkok", "Bangkok", "10200", 13.7563, 100.5018));
        locations.add(new Location("Vietnam", "VN", "Hanoi", "Hanoi", "100000", 21.0278, 105.8342));
        locations.add(new Location("Indonesia", "ID", "Jakarta", "Jakarta", "10110", -6.2088, 106.8456));
        locations.add(new Location("Malaysia", "MY", "Kuala Lumpur", "Kuala Lumpur", "50088", 3.1390, 101.6869));
        locations.add(new Location("Philippines", "PH", "National Capital Region, Metro Manila, Quezon City",
                "Quezon City", "1100", 14.6760, 121.0437));
        locations.add(new Location("Egypt", "EG", "Cairo", "Cairo", "11511", 30.0444, 31.2357));
        locations.add(new Location("Nigeria", "NG", "Lagos", "Lagos", "100001", 6.5244, 3.3792));
        locations.add(new Location("Kenya", "KE", "Nairobi", "Nairobi", "00100", -1.2921, 36.8219));
        locations.add(new Location("Ghana", "GH", "Greater Accra", "Accra", "00233", 5.6037, -0.1870));
        locations.add(new Location("Morocco", "MA", "Casablanca-Settat", "Casablanca", "20250", 33.5731, -7.5898));
        locations.add(new Location("Tunisia", "TN", "Tunis", "Tunis", "1000", 36.8065, 10.1815));
        locations.add(new Location("Algeria", "DZ", "Algiers", "Algiers", "16000", 36.7372, 3.0408));
        locations.add(new Location("Peru", "PE", "Lima", "Lima", "15001", -12.0464, -77.0428));
        locations.add(
                new Location("Chile", "CL", "Santiago Metropolitan Region", "Santiago", "8320000", -33.4489, -70.6693));
        locations.add(new Location("Colombia", "CO", "Bogota", "Bogota", "111711", 4.7109, -74.0721));
        locations.add(new Location("Venezuela", "VE", "Caracas", "Caracas", "1010", 10.4806, -66.9036));
        locations.add(new Location("Ecuador", "EC", "Pichincha", "Quito", "170136", -0.1807, -78.4678));
        locations.add(new Location("Uruguay", "UY", "Montevideo", "Montevideo", "11000", -34.9011, -56.1645));
        locations.add(new Location("Paraguay", "PY", "Asuncion", "Asuncion", "1001", -25.2637, -57.5759));
        locations.add(new Location("Bolivia", "BO", "La Paz", "La Paz", "0000", -16.2902, -63.5887));
        locations.add(new Location("Panama", "PA", "Panama", "Panama City", "00000", 8.9824, -79.5199));
        locations.add(new Location("Costa Rica", "CR", "San Jose", "San Jose", "10101", 9.9281, -84.0907));
        locations.add(new Location("El Salvador", "SV", "San Salvador", "San Salvador", "01101", 13.6929, -89.2182));
        locations.add(new Location("Honduras", "HN", "Francisco Morazan", "Tegucigalpa", "11101", 14.0723, -87.1921));
        locations.add(new Location("Nicaragua", "NI", "Managua", "Managua", "11001", 12.1149, -86.2362));
        locations.add(new Location("Guatemala", "GT", "Guatemala", "Guatemala City", "01001", 14.6349, -90.5069));
        locations.add(
                new Location("Dominican Republic", "DO", "Santo Domingo", "Santo Domingo", "10101", 18.4861, -69.9312));
        locations.add(new Location("Puerto Rico", "PR", "San Juan", "San Juan", "00901", 18.4655, -66.1057));
        locations.add(new Location("Jamaica", "JM", "Kingston", "Kingston", "00000", 18.0179, -76.8099));
        locations.add(new Location("Trinidad and Tobago", "TT", "Port of Spain", "Port of Spain", "00000", 10.6918,
                -61.2225));
        locations.add(new Location("Barbados", "BB", "Saint Michael", "Bridgetown", "00000", 13.1132, -59.5988));
        locations.add(new Location("Bahamas", "BS", "New Providence", "Nassau", "00000", 25.0343, -77.3963));
        locations.add(new Location("Cuba", "CU", "Havana", "Havana", "10100", 23.1136, -82.3666));
        locations.add(new Location("Haiti", "HT", "Ouest", "Port-au-Prince", "6110", 18.5944, -72.3074));
        locations.add(new Location("Guyana", "GY", "Demerara-Mahaica", "Georgetown", "00000", 6.8013, -58.1551));
        locations.add(new Location("Suriname", "SR", "Paramaribo", "Paramaribo", "00000", 5.8520, -55.2038));
        locations.add(new Location("French Guiana", "GF", "Cayenne", "Cayenne", "97300", 4.9224, -52.3135));
        locations.add(new Location("Guadeloupe", "GP", "Basse-Terre", "Basse-Terre", "97100", 16.0444, -61.7333));
        locations.add(new Location("Martinique", "MQ", "Fort-de-France", "Fort-de-France", "97200", 14.6161, -61.0586));

        return locations;

    }

    /**
     * Generates a random income level from a predefined set of income ranges.
     *
     * @return A randomly selected income level as a String.
     */
    public static String randomIncomeLevel() {
        String[] incomeLevels = { "$10,000-$14,999", "$15,000-$19,999", "$20000 - $39999", "$40000 - $49999",
                "$50000 - $74999", "$75000 - $99999", "$100000 - $149999", "$150,000-$174,999", "$175,000-$199,999",
                "$200,000-$249,999", "$250,000+" };
        Random random = new Random();
        int index = random.nextInt(incomeLevels.length);
        return incomeLevels[index];
    }

    /**
     * Generates a random age between 21 (inclusive) and 75 (inclusive).
     *
     * @return a random integer representing an age between 21 and 75.
     */
    public static int randomAge() {
        return ThreadLocalRandom.current().nextInt(21, 76);
    }

    /**
     * Generates a random age range from a predefined set of age ranges.
     *
     * @return A randomly selected age range as a String.
     */
    public static String randomAgeRange() {
        String[] ageRanges = { "13-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+" };
        Random random = new Random();
        int index = random.nextInt(ageRanges.length);
        return ageRanges[index];
    }

    /**
     * Generates a random Demographics object with random values for gender, age
     * range, income level, education level, employment status, and marital status.
     *
     * @return a Demographics object populated with random values.
     */
    public static Demographics randomDemographics() {
        String incomeLevel = randomIncomeLevel();
        String ageRange = randomAgeRange();
        String educationLevel = randomEducationLevel();
        String employmentStatus = randomEmploymentStatus();
        String maritalStatus = randomMaritalStatus();
        Gender gender = randomGender();

        return new Demographics(gender, ageRange, incomeLevel, educationLevel, employmentStatus, maritalStatus);
    }

    /**
     * Generates a random education level from a predefined list of education
     * levels.
     *
     * @return A randomly selected education level as a String. The possible values
     *         are: "High School", "Some College", "Associates Degree", "Bachelors
     *         Degree", "Masters Degree", and "Doctorate".
     */
    public static String randomEducationLevel() {
        String[] educationLevels = { "High School", "Some College", "Associates Degree", "Bachelors Degree",
                "Masters Degree", "Doctorate" };
        Random random = new Random();
        int index = random.nextInt(educationLevels.length);
        return educationLevels[index];
    }

    /**
     * Generates a random employment status from a predefined list of statuses.
     *
     * @return A randomly selected employment status, which can be one of the
     *         following: "Employed", "Unemployed", "Retired", "Student", or
     *         "Homemaker".
     */
    public static String randomEmploymentStatus() {
        String[] employmentStatuses = { "Employed", "Unemployed", "Retired", "Student", "Homemaker" };
        Random random = new Random();
        int index = random.nextInt(employmentStatuses.length);
        return employmentStatuses[index];
    }

    /**
     * Generates a random marital status from a predefined list of statuses.
     *
     * @return A randomly selected marital status, which can be "Single", "Married",
     *         "Divorced", or "Widowed".
     */
    public static String randomMaritalStatus() {
        String[] maritalStatuses = { "Single", "Married", "Divorced", "Widowed" };
        Random random = new Random();
        int index = random.nextInt(maritalStatuses.length);
        return maritalStatuses[index];
    }

    /**
     * Generates a random Gender value.
     *
     * This method selects a random value from the Gender enum.
     *
     * @return a randomly selected Gender value
     */
    public static Gender randomGender() {
        Gender[] genders = Gender.values();
        Random random = new Random();
        int index = random.nextInt(genders.length);
        return genders[index];
    }

    /**
     * Generates a random Location object from the list of available locations.
     *
     * @return a randomly selected Location object from the locations list.
     */
    public static Location randomLocation() {
        int index = ThreadLocalRandom.current().nextInt(locations.size());
        return locations.get(index);
    }

    /**
     * Generates a random Campaign object with the following properties: - A unique
     * identifier (UUID) for the campaign. - A unique identifier (UUID) for the
     * advertiser. - A name in the format "Campaign X" where X is a random number
     * between 1 and 100. - A start date set to 50 days before the current date. -
     * An end date set to 365 days after the current date. - A budget randomly
     * chosen between 500 and 5000 (inclusive).
     *
     * @return A randomly generated Campaign object.
     */
    public static Campaign randomCampaign() {
        Date today = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(today);
        cal.add(Calendar.DAY_OF_YEAR, -50);
        Date startDate = cal.getTime();
        cal.setTime(today);
        cal.add(Calendar.DAY_OF_YEAR, 365);
        Date endDate = cal.getTime();

        int budget = ThreadLocalRandom.current().nextInt(500, 5001);
        String id = UUID.randomUUID().toString();
        String advertiserId = UUID.randomUUID().toString();
        String name = "Campaign " + ThreadLocalRandom.current().nextInt(1, 101);
        return new Campaign(id, name, advertiserId, startDate, endDate, budget);
    }

    /**
     * Generates a list of Lineitem objects for a given campaign.
     *
     * @param lineitemCount the number of Lineitem objects to generate
     * @param campaign      the Campaign object for which the Lineitem objects are
     *                      generated
     * @return a list of generated Lineitem objects
     */
    public static List<Lineitem> generateLineitems(int lineitemCount, Campaign campaign) {
        List<Lineitem> lineitems = new ArrayList<>();
        for (int i = 0; i < lineitemCount; i++) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(campaign.getEndDate());
            cal.add(Calendar.DAY_OF_YEAR, -30);
            Date endDateMinus30 = cal.getTime();
            Date startDate = randomDateBetween(campaign.getStartDate(), endDateMinus30);

            cal.setTime(startDate);
            cal.add(Calendar.DAY_OF_YEAR, 30);
            Date endDatePlus30 = cal.getTime();
            Date endDate = endDatePlus30.before(campaign.getEndDate()) ? endDatePlus30 : campaign.getEndDate();
            String id = UUID.randomUUID().toString();
            String campaignId = campaign.getId();
            String name = campaign.getName() + " - Lineitem " + id;
            int budget = ThreadLocalRandom.current().nextInt(20, 100);
            Lineitem lineitem = new Lineitem(id, campaignId, name, startDate, endDate, budget);
            LineitemStatus status = LineitemStatus.values()[ThreadLocalRandom.current()
                    .nextInt(LineitemStatus.values().length)];
            lineitem.setStatus(status);
            lineitems.add(lineitem);
        }
        return lineitems;
    }

    /**
     * Generates a list of random banner sizes from the available IAB banner sizes.
     * The method randomly selects sizes from the list of available sizes and
     * removes them from the original list to ensure no duplicates.
     *
     * @return a list of randomly selected banner sizes.
     */
    public static List<Size> randomBannerSizes() {
        Random random = new Random();
        List<Size> availableSizes = iabBannerSizes;

        List<Size> selectedSizes = new ArrayList<>();

        for (int i = 0; i < availableSizes.size(); i++) {
            int index = random.nextInt(availableSizes.size());
            selectedSizes.add(availableSizes.remove(index));
        }

        return selectedSizes;
    }

    /**
     * Generates a random Creative object with the specified advertiser and line
     * item IDs. The Creative object will have a unique ID, a name based on that ID,
     * a URL derived from the name, and a type set to "image". The sizes of the
     * creative will be randomly generated.
     *
     * @param advertiserId the ID of the advertiser associated with the creative
     * @param lineitemId   the ID of the line item associated with the creative
     * @return a randomly generated Creative object
     */
    public static Creative randomCreative(String advertiserId, String lineitemId) {
        String id = UUID.randomUUID().toString();
        String name = "Creative " + id;
        String url = "http://www." + name.replace(" ", "").toLowerCase() + ".com";
        String type = "image";
        Creative creative = new Creative(id, name, url, advertiserId, lineitemId, type);
        creative.setSizes(randomBannerSizes());
        return creative;
    }

    /**
     * Returns a list of standard IAB (Interactive Advertising Bureau) banner sizes.
     * These sizes are commonly used in online advertising.
     *
     * @return a list of {@link Size} objects representing standard IAB banner
     *         sizes. The sizes included are:
     *         <ul>
     *         <li>468x60 - Full Banner</li>
     *         <li>728x90 - Leaderboard</li>
     *         <li>300x250 - Medium Rectangle</li>
     *         <li>336x280 - Large Rectangle</li>
     *         <li>120x600 - Skyscraper</li>
     *         <li>160x600 - Wide Skyscraper</li>
     *         <li>300x600 - Half Page</li>
     *         <li>970x90 - Large Leaderboard</li>
     *         <li>320x50 - Mobile Leaderboard</li>
     *         <li>300x50 - Mobile Banner</li>
     *         <li>320x100 - Large Mobile Banner</li>
     *         </ul>
     */
    private static List<Size> getIABBannerSizes() {
        List<Size> sizes = new ArrayList<>();
        sizes.add(new Size(468, 60)); // Full Banner
        sizes.add(new Size(728, 90)); // Leaderboard
        sizes.add(new Size(300, 250)); // Medium Rectangle
        sizes.add(new Size(336, 280)); // Large Rectangle
        sizes.add(new Size(120, 600)); // Skyscraper
        sizes.add(new Size(160, 600)); // Wide Skyscraper
        sizes.add(new Size(300, 600)); // Half Page
        sizes.add(new Size(970, 90)); // Large Leaderboard
        sizes.add(new Size(320, 50)); // Mobile Leaderboard
        sizes.add(new Size(300, 50)); // Mobile Banner
        sizes.add(new Size(320, 100)); // Large Mobile Banner
        return sizes;
    }

    /**
     * Generates a random date between the specified start (inclusive) and end
     * (exclusive) dates.
     *
     * @param startInclusive the start date (inclusive)
     * @param endExclusive   the end date (exclusive)
     * @return a randomly generated date between the start and end dates
     */
    private static Date randomDateBetween(Date startInclusive, Date endExclusive) {
        long startEpoch = startInclusive.getTime();
        long endEpoch = endExclusive.getTime();
        long randomEpoch = ThreadLocalRandom.current().nextLong(startEpoch, endEpoch);
        return new Date(randomEpoch);
    }

    /**
     * Generates a random Publisher object with a unique ID, name, domain, and a
     * list of random ad categories.
     *
     * @return a Publisher object with randomly generated attributes.
     */
    public static Publisher randomBidRequestPublisher() {
        String id = UUID.randomUUID().toString();
        String name = "Publisher " + id;
        String domain = name.replace(" ", "").toLowerCase() + ".com";

        List<String> categories = randomAdCategories(3, 6);

        Publisher publisher = new Publisher(id, name, domain, categories, null, null);
        return publisher;
    }

    /**
     * Generates a list of random advertisement categories.
     *
     * @param origin the lower bound (inclusive) for the number of categories to
     *               generate
     * @param bound  the upper bound (exclusive) for the number of categories to
     *               generate
     * @return a list of randomly selected advertisement categories
     */
    public static List<String> randomAdCategories(int origin, int bound) {
        List<String> categories = new ArrayList<String>();
        Random random = new Random();
        int categoryCount = ThreadLocalRandom.current().nextInt(origin, bound);
        for (int i = 0; i < categoryCount; i++) {
            int index = random.nextInt(iabContentCategories.size());
            categories.add(iabContentCategories.get(index));
        }
        return categories;
    }

    /**
     * Generates a list of IAB (Interactive Advertising Bureau) content categories.
     * These categories represent various topics and interests that can be used for
     * categorizing content in real-time bidding scenarios.
     *
     * @return a list of strings representing IAB content categories.
     */
    public static List<String> iabContentCatergories() {
        List<String> categories = new ArrayList<>();
        categories.add("Arts & Entertainment");
        categories.add("Automotive");
        categories.add("Business");
        categories.add("Careers");
        categories.add("Education");
        categories.add("Family & Parenting");
        categories.add("Health & Fitness");
        categories.add("Food & Drink");
        categories.add("Hobbies & Interests");
        categories.add("Home & Garden");
        categories.add("Law, Gov't & Politics");
        categories.add("News");
        categories.add("Personal Finance");
        categories.add("Pets");
        categories.add("Real Estate");
        categories.add("Science");
        categories.add("Shopping");
        categories.add("Society");
        categories.add("Sports");
        categories.add("Technology & Computing");
        categories.add("Travel");
        return categories;
    }

    /**
     * Generates a random BidRequest object with various randomly generated fields.
     *
     * @param startUserId the starting range for generating a random user ID
     * @param endUserId   the ending range for generating a random user ID
     * @return a BidRequest object populated with random data
     */
    public static BidRequest randomBidRequest(long startUserId, long endUserId) {
        Publisher publisher = randomBidRequestPublisher();
        String id = UUID.randomUUID().toString();
        String userId = String.valueOf(ThreadLocalRandom.current().nextLong(startUserId, endUserId + 1));
        String auctionId = UUID.randomUUID().toString();
        String siteId = UUID.randomUUID().toString();
        String appId = UUID.randomUUID().toString();
        String deviceId = UUID.randomUUID().toString();
        String ipAddress = "192.168.1." + ThreadLocalRandom.current().nextInt(1, 255);
        String userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3";
        String adUnitCode = "adunit-" + ThreadLocalRandom.current().nextInt(1, 100);
        List<String> adFormats = List.of("banner", "video");
        List<String> adSizes = List.of("300x250", "728x90");
        List<String> adCategories = randomAdCategories(1, 4);
        List<String> adKeywords = List.of("sports", "technology");
        String bidFloor = "0.50";
        String currency = "USD";
        String country = "US";
        String region = "CA";
        String city = "Los Angeles";
        String zip = "90001";
        double latitude = 34.0522;
        double longitude = -118.2437;

        BidRequest bidRequest = new BidRequest(id, userId, auctionId, siteId, appId, deviceId, ipAddress, userAgent,
                adUnitCode, adFormats, adSizes, adCategories, adKeywords, bidFloor, currency, country, region, city,
                zip, latitude, longitude, publisher);

        return bidRequest;
    }

    /**
     * Generates a random BidResponse based on the provided BidRequest and Lineitem.
     *
     * @param bidRequest the bid request containing details about the ad unit and
     *                   bid floor
     * @param lineitem   the line item containing details about the ad campaign
     * @return a BidResponse object containing a randomly generated bid
     */
    public static BidResponse randomBidResponse(BidRequest bidRequest, Lineitem lineitem) {
        Bid bid = new Bid(UUID.randomUUID().toString(), bidRequest.getId(), bidRequest.getAdUnitCode(),
                bidRequest.getBidFloor(), bidRequest.getCurrency(),
                randomCreative(UUID.randomUUID().toString(), UUID.randomUUID().toString()).getId(),
                randomLocation().getCountry(), randomLocation().getRegion(), randomLocation().getCity(),
                randomLocation().getPostalCode(), randomLocation().getLatitude(), randomLocation().getLongitude());
        List<Bid> bids = new ArrayList<Bid>();
        bids.add(bid);
        SeatBid seatBid = new SeatBid("12345", bids);
        List<SeatBid> seatBids = new ArrayList<SeatBid>();
        seatBids.add(seatBid);
        BidResponse response = new BidResponse(bidRequest.getId(), "USD", seatBids);

        return response;
    }

    public static List<String> randomInterests() {
        Random random = new Random();
        int interestCount = ThreadLocalRandom.current().nextInt(3, 8);
        List<String> interests = new ArrayList<>();
        for (int i = 0; i < interestCount; i++) {
            int index = random.nextInt(iabContentCategories.size());
            interests.add(iabContentCategories.get(index));
        }
        return interests;
    }
}
